# description: configuration file path, if it's specified as relative path,
# then directory of binary file will be the base directory of configuration file,
# it is recommended to specify absolute path.
# command-line-argument: --config
# type: string
# default: None
config: crypto.yaml

# log configuration
log:
  # description: log level
  # command-line-argument: --log-level
  # type: string
  # available: [debug, info, warn, error, fatal]
  # default: info
  level: info
  # description: log format
  # command-line-argument: --log-format
  # type: string
  # available: [text, json]
  # default: text
  format: text

# table configuration
table:
  # description: only tables included in this list will be processed
  # command-line-argument: --table-include
  # type: list
  # default: None
  include: ""
  # description: tables excluded in this list will be ignored, this is higher priority than include
  # command-line-argument: --table-exclude
  # type: list
  # default: None
  exclude: ""

# source configuration
source:
  # description: source type
  # command-line-argument: --source-type
  # type: string
  # available: [file, db]
  # default: file
  type: file
  # description: source file path, if it's specified as relative path,
  # then directory of binary file will be the base directory of source file,
  # it is recommended to specify absolute path.
  # command-line-argument: --source-file
  # type: string
  # default: None
  file: ""
  # source db configuration
  db:
    # description: source database address
    # command-line-argument: --source-db-addr
    # type: string
    # default: 127.0.0.1:3306
    addr: 127.0.0.1:3306
    # description: source database name
    # command-line-argument: --source-db-name
    # type: string
    # default: None
    name: gp
    # description: source database user
    # command-line-argument: --source-db-user
    # type: string
    # default: None
    user: root
    # description: source database password
    # command-line-argument: --source-db-pass
    # type: string
    # default: None
    pass: root

target:
  # description: target type
  # command-line-argument: --target-type
  # type: string
  # available: [file, db]
  # default: file
  type: file
  # description: target file path, if it's specified as relative path,
  # then directory of binary file will be the base directory of target file,
  # it is recommended to specify absolute path.
  # command-line-argument: --target-file
  # type: string
  # default: None
  file: ""
  # target db configuration
  db:
    # description: target database address
    # command-line-argument: --target-db-addr
    # type: string
    # default: 127.0.0.1:3306
    addr: 192.168.137.11:3306
    # description: target database name
    # command-line-argument: --target-db-name
    # type: string
    # default: None
    name: gp
    # description: target database user
    # command-line-argument: --target-db-user
    # type: string
    # default: None
    user: root
    # description: target database password
    # command-line-argument: --target-db-pass
    # type: string
    # default: None
    pass: root
    # description: target database tables
    # command-line-argument: --target-db-tables
    # type: list
    # default: None
    table: ""


